# Generated by Claude Code
"""Tests for classify-guides.py heuristics and classification logic."""

import sys
from pathlib import Path

import pytest

# Import from hyphenated filename using importlib
import importlib
sys.path.insert(0, str(Path(__file__).parent.parent))
_mod = importlib.import_module("classify-guides")
analyze_adoc = _mod.analyze_adoc
classify = _mod.classify
merge_classification = _mod.merge_classification


# ---------------------------------------------------------------------------
# Fixtures: create temp .adoc files for testing
# ---------------------------------------------------------------------------

def write_adoc(tmp_path: Path, filename: str, content: str) -> Path:
    """Write an .adoc file and return its path."""
    f = tmp_path / filename
    f.write_text(content, encoding="utf-8")
    return f


# ---------------------------------------------------------------------------
# Tests for analyze_adoc()
# ---------------------------------------------------------------------------

class TestAnalyzeAdoc:
    """Tests for structural analysis of .adoc files."""

    def test_extracts_title(self, tmp_path):
        f = write_adoc(tmp_path, "test.adoc", "= My Guide Title\n\nSome content.\n")
        result = analyze_adoc(f)
        assert result["title"] == "My Guide Title"

    def test_extracts_diataxis_type(self, tmp_path):
        content = "= Title\n:diataxis-type: howto\n\nContent here.\n"
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["diataxis_type"] == "howto"

    def test_diataxis_type_case_insensitive(self, tmp_path):
        content = "= Title\n:diataxis-type: Tutorial\n\nContent.\n"
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["diataxis_type"] == "tutorial"

    def test_no_diataxis_type(self, tmp_path):
        content = "= Title\n\nContent here.\n"
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["diataxis_type"] == ""

    def test_diataxis_type_only_from_header(self, tmp_path):
        """Ensure :diataxis-type: in body text (after first blank line) is NOT captured."""
        content = (
            "= Title\n\n"  # blank line ends header
            "Some content.\n\n"
            ":diataxis-type: howto\n"  # this is in the body, not header
        )
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["diataxis_type"] == ""

    def test_counts_code_blocks(self, tmp_path):
        content = "= Title\n\n[source,java]\n----\ncode\n----\n\n[source,xml]\n----\nmore\n----\n"
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["code_block_count"] == 2

    def test_counts_sections(self, tmp_path):
        content = "= Title\n\n== Section 1\n\nText.\n\n== Section 2\n\nText.\n\n=== Subsection\n\nText.\n"
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["section_count"] == 2  # only level-2 sections

    def test_detects_tutorial_signals(self, tmp_path):
        content = (
            "= Getting Started\n\n"
            "== Prerequisites\n\nJava 17.\n\n"
            "== Creating the Maven project\n\nText.\n\n"
            "include::{includes}/devtools/create-app.adoc[]\n\n"
            "== Running the application\n\nText.\n"
        )
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert len(result["tutorial_signals"]) >= 3
        assert result["devtools_includes"] == 1

    def test_detects_reference_signals(self, tmp_path):
        content = (
            "= Config Reference\n\n"
            "== Configuration Reference\n\n"
            "include::{generated-dir}/config/quarkus-foo.adoc[]\n\n"
            "[cols=\"80,10,10\"]\n|===\n| col1 | col2\n|===\n"
        )
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert len(result["reference_signals"]) >= 2
        assert result["config_table_count"] >= 1

    def test_detects_procedure_heading(self, tmp_path):
        content = "= Configure X\n\n== Procedure\n\n. Do step 1.\n. Do step 2.\n. Do step 3.\n"
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["has_procedure_heading"] is True
        assert result["ordered_step_count"] >= 3

    def test_detects_concept_headings(self, tmp_path):
        content = (
            "= Security architecture\n\n"
            "== Overview\n\nText.\n\n"
            "== How authentication works\n\nMore text.\n"
        )
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["concept_heading_count"] >= 2

    def test_detects_diagrams(self, tmp_path):
        content = "= Architecture\n\nimage::arch-diagram.png[Architecture]\n\nText.\n"
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["diagram_count"] == 1

    def test_captures_prose_sample(self, tmp_path):
        content = "= Title\n:some-attr: value\n\nThis is the first real paragraph of content.\n"
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["prose_sample"] == "This is the first real paragraph of content."

    def test_file_not_found(self, tmp_path):
        result = analyze_adoc(tmp_path / "nonexistent.adoc")
        assert "error" in result

    def test_imperative_sentences_not_counted_in_code(self, tmp_path):
        content = (
            "= Title\n\n"
            "Create a file.\n\n"  # counted
            "[source,java]\n----\n"
            "Create something;\n"  # NOT counted (in code block)
            "----\n"
        )
        f = write_adoc(tmp_path, "test.adoc", content)
        result = analyze_adoc(f)
        assert result["imperative_sentence_count"] == 1


# ---------------------------------------------------------------------------
# Tests for classify()
# ---------------------------------------------------------------------------

class TestClassify:
    """Tests for the classification logic."""

    def _base_analysis(self, **overrides) -> dict:
        """Create a minimal analysis dict with sensible defaults."""
        base = {
            "title": "Some Guide",
            "diataxis_type": "",
            "total_lines": 300,
            "section_count": 5,
            "sections": [],
            "code_block_count": 5,
            "tutorial_signals": [],
            "reference_signals": [],
            "howto_signals": [],
            "config_table_count": 0,
            "generated_config_includes": [],
            "devtools_includes": 0,
            "ordered_step_count": 0,
            "imperative_sentence_count": 0,
            "has_procedure_heading": False,
            "concept_heading_count": 0,
            "explanatory_sentence_count": 0,
            "diagram_count": 0,
            "xref_count": 0,
            "prose_sample": "",
            "filename": "some-guide.adoc",
        }
        base.update(overrides)
        return base

    def test_metadata_takes_precedence(self):
        analysis = self._base_analysis(
            diataxis_type="howto",
            tutorial_signals=[(10, "heading"), (20, "heading"), (30, "heading")],
        )
        result = classify(analysis)
        assert result["suggested_type"] == "howto"
        assert result["confidence"] == "high"
        assert result["source"] == "metadata"

    def test_metadata_tutorial(self):
        analysis = self._base_analysis(diataxis_type="tutorial")
        result = classify(analysis)
        assert result["suggested_type"] == "tutorial"
        assert result["source"] == "metadata"

    def test_metadata_concept(self):
        analysis = self._base_analysis(diataxis_type="concept")
        result = classify(analysis)
        assert result["suggested_type"] == "concept"
        assert result["source"] == "metadata"

    def test_metadata_reference(self):
        analysis = self._base_analysis(diataxis_type="reference")
        result = classify(analysis)
        assert result["suggested_type"] == "reference"
        assert result["source"] == "metadata"

    def test_invalid_metadata_falls_through(self):
        analysis = self._base_analysis(diataxis_type="core")
        result = classify(analysis)
        assert result["source"] == "heuristic"  # not metadata

    def test_tutorial_from_signals(self):
        analysis = self._base_analysis(
            tutorial_signals=[
                (10, "heading: Prerequisites"),
                (20, "heading: Creating the Maven project"),
                (30, "heading: Running the application"),
            ],
            devtools_includes=1,
        )
        result = classify(analysis)
        assert result["suggested_type"] == "tutorial"
        assert result["confidence"] in ("high", "medium")

    def test_reference_from_title(self):
        analysis = self._base_analysis(
            title="Configuration Reference",
            generated_config_includes=[100, 200],
            config_table_count=5,
        )
        result = classify(analysis)
        assert result["suggested_type"] == "reference"

    def test_howto_from_procedure_heading(self):
        analysis = self._base_analysis(
            has_procedure_heading=True,
            ordered_step_count=5,
            imperative_sentence_count=8,
        )
        result = classify(analysis)
        assert result["suggested_type"] == "howto"

    def test_howto_from_filename_suffix(self):
        analysis = self._base_analysis(
            filename="security-oidc-howto.adoc",
            ordered_step_count=3,
        )
        result = classify(analysis)
        assert result["suggested_type"] == "howto"
        assert result["source"] == "heuristic"

    def test_concept_from_title_and_headings(self):
        analysis = self._base_analysis(
            title="Quarkus Security architecture",
            concept_heading_count=3,
            explanatory_sentence_count=10,
            code_block_count=1,
            total_lines=150,
        )
        result = classify(analysis)
        assert result["suggested_type"] == "concept"

    def test_mixed_tutorial_reference(self):
        analysis = self._base_analysis(
            tutorial_signals=[
                (10, "heading"), (20, "heading"), (30, "heading"),
            ],
            devtools_includes=1,
            reference_signals=[
                (200, "heading"), (300, "generated config"),
            ],
            generated_config_includes=[300],
            config_table_count=4,
        )
        result = classify(analysis)
        assert result["suggested_type"].startswith("mixed:")
        assert "tutorial" in result["suggested_type"]
        assert "reference" in result["suggested_type"]

    def test_error_analysis(self):
        result = classify({"error": "File not found"})
        assert result["suggested_type"] == "unknown"
        assert result["confidence"] == "none"

    def test_unclassified_guide(self):
        analysis = self._base_analysis(
            total_lines=50,
            code_block_count=1,
            section_count=1,
        )
        result = classify(analysis)
        # With minimal signals, concept gets score=1 (moderate size) which is
        # below SCORE_THRESHOLD=2, so it falls through to unclassified "guide"
        assert result["suggested_type"] == "guide"
        assert result["confidence"] == "none"
        assert result["source"] == "heuristic"


# ---------------------------------------------------------------------------
# Tests for merge_classification()
# ---------------------------------------------------------------------------

class TestMergeClassification:
    """Tests for merging heuristic and LLM classifications."""

    def test_high_confidence_heuristic_wins(self):
        heuristic = {
            "suggested_type": "tutorial",
            "confidence": "high",
            "reason": "3 tutorial signals",
            "source": "heuristic",
        }
        llm = {"type": "howto", "confidence": "high", "reason": "LLM says howto"}
        result = merge_classification(heuristic, llm)
        assert result["suggested_type"] == "tutorial"
        assert result["llm_agrees"] is False

    def test_agreement_boosts_confidence(self):
        heuristic = {
            "suggested_type": "howto",
            "confidence": "medium",
            "reason": "procedure heading",
            "source": "heuristic",
        }
        llm = {"type": "howto", "confidence": "high", "reason": "task-oriented"}
        result = merge_classification(heuristic, llm)
        assert result["suggested_type"] == "howto"
        assert result["confidence"] == "high"
        assert result["llm_agrees"] is True

    def test_low_heuristic_defers_to_llm(self):
        heuristic = {
            "suggested_type": "guide",
            "confidence": "none",
            "reason": "no signals",
            "source": "heuristic",
        }
        llm = {"type": "concept", "confidence": "high", "reason": "explanatory content"}
        result = merge_classification(heuristic, llm)
        assert result["suggested_type"] == "concept"
        assert result["confidence"] == "medium"  # capped
        assert result["source"] == "llm"

    def test_medium_disagreement_reports_both(self):
        heuristic = {
            "suggested_type": "howto",
            "confidence": "medium",
            "reason": "some signals",
            "source": "heuristic",
        }
        llm = {"type": "tutorial", "confidence": "medium", "reason": "learning-oriented"}
        result = merge_classification(heuristic, llm)
        assert result["suggested_type"] == "howto"  # heuristic kept
        assert result["llm_agrees"] is False
        assert result["llm_type"] == "tutorial"
