# Generated by Claude Code
"""
LLM-based Diataxis classification for AsciiDoc guides.

Provides optional LLM classification as a fallback for guides that
cannot be confidently classified by structural heuristics alone.
Uses Google Gemini, Anthropic Claude, or local Ollama -- whichever
API key / endpoint is available.

No new dependencies: all LLM calls use urllib.request.
"""

import hashlib
import json
import os
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional


DIATAXIS_PROMPT = """\
You are a documentation specialist classifying technical documentation \
by Diataxis type. Analyze the following AsciiDoc document summary and \
classify it as exactly one of: tutorial, howto, concept, reference.

Definitions:
- tutorial: Learning-oriented. Step-by-step lesson that takes a beginner \
from zero to a working result. Has "Prerequisites", "Creating the project", \
"Running the application" sections. Contains devtools/build includes.
- howto: Task-oriented. Practical steps to accomplish a specific goal. \
Assumes existing knowledge. Has "Procedure" or task-oriented sections. \
Uses ordered lists with imperative verbs. Focused on a single task, not learning.
- concept: Understanding-oriented. Explains what something is and how it works. \
Contains architecture diagrams, overviews, discusses design decisions and \
trade-offs. Few code blocks relative to explanatory prose.
- reference: Information-oriented. Technical descriptions, configuration \
properties, API documentation. Contains tables of settings, generated \
configuration, lists of options.

Document summary:
Title: {title}
Filename: {filename}
Total lines: {total_lines}
Level-2 sections: {section_count}
Code blocks: {code_block_count}
Section headings: {headings}
First paragraph: {prose_sample}

Respond with ONLY a JSON object (no markdown fencing):
{{"type": "<type>", "confidence": "<high|medium|low>", "reason": "<brief explanation>"}}\
"""


class LLMClassifier:
    """Classifies documents using an LLM API."""

    def __init__(
        self,
        provider: str = "auto",
        api_key: Optional[str] = None,
        cache_dir: Optional[Path] = None,
        rate_limit_delay: float = 1.0,
    ):
        self._provider_pref = provider
        self._api_key = api_key
        self._cache_dir = (
            cache_dir
            or Path.home() / ".cache" / "doc-utils" / "llm-classifications"
        )
        self._cache_dir.mkdir(parents=True, exist_ok=True)
        self._rate_limit_delay = rate_limit_delay
        self._last_request_time = 0.0
        self._request_count = 0

        self._resolved_provider = self._resolve_provider()

    @property
    def provider_name(self) -> str:
        return self._resolved_provider

    def _resolve_provider(self) -> str:
        """Determine which provider to use."""
        if self._provider_pref != "auto":
            return self._provider_pref

        # Auto-detect based on explicit key, env vars, or local Ollama
        if self._api_key:
            # Guess provider from key prefix
            if self._api_key.startswith("AIza"):
                return "gemini"
            if self._api_key.startswith("sk-ant-"):
                return "anthropic"
            return "gemini"  # default assumption

        if os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY"):
            return "gemini"
        if os.environ.get("ANTHROPIC_API_KEY"):
            return "anthropic"

        # Check if Ollama is running locally
        try:
            urllib.request.urlopen(
                "http://localhost:11434/api/tags", timeout=2
            )
            return "ollama"
        except Exception:
            pass

        return "none"

    def _get_api_key(self) -> str:
        """Get the API key for the resolved provider."""
        if self._api_key:
            return self._api_key
        if self._resolved_provider == "gemini":
            return os.environ.get("GEMINI_API_KEY") or os.environ.get(
                "GOOGLE_API_KEY", ""
            )
        if self._resolved_provider == "anthropic":
            return os.environ.get("ANTHROPIC_API_KEY", "")
        return ""

    def is_available(self) -> bool:
        return self._resolved_provider != "none"

    # ----- Caching -----

    def _cache_key(self, analysis: dict) -> str:
        """Generate cache key from document characteristics."""
        content = (
            f"{analysis.get('filename', '')}:"
            f"{analysis.get('title', '')}:"
            f"{analysis.get('total_lines', 0)}:"
            f"{analysis.get('section_count', 0)}:"
            f"{analysis.get('code_block_count', 0)}:"
            f"{self._resolved_provider}"
        )
        return hashlib.md5(content.encode()).hexdigest()

    def _check_cache(self, key: str) -> Optional[dict]:
        cache_file = self._cache_dir / f"{key}.json"
        if cache_file.exists():
            try:
                return json.loads(cache_file.read_text())
            except (json.JSONDecodeError, OSError):
                return None
        return None

    def _write_cache(self, key: str, result: dict):
        cache_file = self._cache_dir / f"{key}.json"
        try:
            cache_file.write_text(json.dumps(result))
        except OSError:
            pass  # non-critical

    # ----- Rate limiting -----

    def _rate_limit(self):
        """Enforce rate limiting between API calls."""
        elapsed = time.time() - self._last_request_time
        if elapsed < self._rate_limit_delay:
            time.sleep(self._rate_limit_delay - elapsed)
        self._last_request_time = time.time()
        self._request_count += 1

    # ----- Classification -----

    def classify(self, analysis: dict) -> Optional[dict]:
        """Classify a single document. Returns None on failure."""
        # Check cache first
        key = self._cache_key(analysis)
        cached = self._check_cache(key)
        if cached:
            return cached

        # Build prompt from structural summary (not full file content)
        headings = [h[2] for h in analysis.get("sections", [])[:15]]
        prose_sample = analysis.get("prose_sample", "")

        prompt = DIATAXIS_PROMPT.format(
            title=analysis.get("title", ""),
            filename=analysis.get("filename", ""),
            total_lines=analysis.get("total_lines", 0),
            section_count=analysis.get("section_count", 0),
            code_block_count=analysis.get("code_block_count", 0),
            headings=headings,
            prose_sample=prose_sample[:500],
        )

        # Rate limit and dispatch
        self._rate_limit()
        try:
            result = self._dispatch(prompt)
            if result:
                self._write_cache(key, result)
            return result
        except urllib.error.HTTPError as e:
            if e.code == 429:
                # Rate limited -- wait and retry once
                time.sleep(5)
                try:
                    result = self._dispatch(prompt)
                    if result:
                        self._write_cache(key, result)
                    return result
                except Exception:
                    return {"error": "Rate limited after retry"}
            return {"error": f"HTTP {e.code}: {e.reason}"}
        except Exception as e:
            return {"error": str(e)}

    def _dispatch(self, prompt: str) -> Optional[dict]:
        """Dispatch to the appropriate provider."""
        if self._resolved_provider in ("gemini", "anthropic"):
            if not self._get_api_key():
                return {"error": f"No API key found for {self._resolved_provider}"}
        if self._resolved_provider == "gemini":
            return self._call_gemini(prompt)
        elif self._resolved_provider == "anthropic":
            return self._call_anthropic(prompt)
        elif self._resolved_provider == "ollama":
            return self._call_ollama(prompt)
        return None

    # ----- Provider implementations -----

    def _call_gemini(self, prompt: str) -> Optional[dict]:
        """Call Google Gemini API."""
        api_key = self._get_api_key()
        url = (
            f"https://generativelanguage.googleapis.com/v1beta/"
            f"models/gemini-2.0-flash:generateContent?key={api_key}"
        )
        payload = json.dumps({
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.1,
                "maxOutputTokens": 256,
            },
        }).encode()

        req = urllib.request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())

        text = data["candidates"][0]["content"]["parts"][0]["text"].strip()
        return self._parse_json_response(text)

    def _call_anthropic(self, prompt: str) -> Optional[dict]:
        """Call Anthropic Claude API."""
        api_key = self._get_api_key()
        url = "https://api.anthropic.com/v1/messages"
        payload = json.dumps({
            "model": "claude-haiku-4-5-20251001",
            "max_tokens": 256,
            "messages": [{"role": "user", "content": prompt}],
        }).encode()

        req = urllib.request.Request(
            url,
            data=payload,
            headers={
                "Content-Type": "application/json",
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read())

        text = data["content"][0]["text"].strip()
        return self._parse_json_response(text)

    def _call_ollama(self, prompt: str) -> Optional[dict]:
        """Call local Ollama API."""
        url = "http://localhost:11434/api/generate"
        payload = json.dumps({
            "model": "llama3.2",
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": 0.1},
        }).encode()

        req = urllib.request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read())

        text = data.get("response", "").strip()
        return self._parse_json_response(text)

    def _parse_json_response(self, text: str) -> Optional[dict]:
        """Parse LLM response, handling markdown fencing and whitespace."""
        # Strip markdown code fences if present
        if text.startswith("```"):
            lines = text.split("\n")
            # Remove first and last lines (```json and ```)
            lines = [l for l in lines if not l.strip().startswith("```")]
            text = "\n".join(lines).strip()

        try:
            result = json.loads(text)
            # Validate expected fields
            if "type" in result and result["type"] in (
                "tutorial", "howto", "concept", "reference"
            ):
                return {
                    "type": result["type"],
                    "confidence": result.get("confidence", "medium"),
                    "reason": result.get("reason", ""),
                }
        except json.JSONDecodeError:
            pass

        return {"error": f"Could not parse LLM response: {text[:200]}"}
