#!/usr/bin/env python3
"""Convert Obsidian wiki-links to pandoc-compatible markdown links.

Pre-processes an Obsidian markdown file so that internal heading links
(wiki-link syntax) become standard markdown anchor links that work in
pandoc-generated PDFs.

Converts:
    [[#Heading Text|display text]]  →  [display text](#heading-text)
    [[#Heading Text]]               →  [Heading Text](#heading-text)

The slugification follows pandoc's heading ID algorithm (pandoc manual,
"Heading identifiers" section).

Usage:
    # Pipe into pandoc
    python3 obsidian_to_pandoc.py input.md | pandoc -o output.pdf

    # Write to file
    python3 obsidian_to_pandoc.py input.md -o converted.md

    # Read from stdin
    cat input.md | python3 obsidian_to_pandoc.py

Generated by Claude Code
"""

import argparse
import re
import sys


def pandoc_slugify(heading):
    """Generate a pandoc-compatible heading ID from heading text.

    Follows pandoc's algorithm:
    1. Remove all non-alphanumeric characters except underscores,
       hyphens, and periods (keep spaces for step 2).
    2. Replace each space or newline with a hyphen.
    3. Convert to lowercase.
    4. Remove leading non-letter characters.
    """
    s = heading
    s = re.sub(r'[^\w\s.\-]', '', s)
    s = re.sub(r'[ \t\n]', '-', s)
    s = s.lower()
    s = re.sub(r'^[^a-z]+', '', s)
    return s


def convert_wikilinks(text):
    """Replace Obsidian wiki-links with standard markdown links."""
    # [[#Heading|display]] -> [display](#slug)
    text = re.sub(
        r'\[\[#([^|\]]+)\|([^\]]+)\]\]',
        lambda m: '[{}](#{})'.format(m.group(2), pandoc_slugify(m.group(1))),
        text,
    )
    # [[#Heading]] -> [Heading](#slug)
    text = re.sub(
        r'\[\[#([^\]]+)\]\]',
        lambda m: '[{}](#{})'.format(m.group(1), pandoc_slugify(m.group(1))),
        text,
    )
    return text


def main():
    parser = argparse.ArgumentParser(
        description='Convert Obsidian wiki-links to pandoc markdown links.'
    )
    parser.add_argument('infile', nargs='?', help='Input markdown file (default: stdin)')
    parser.add_argument('-o', '--output', help='Output file (default: stdout)')
    args = parser.parse_args()

    if args.infile:
        with open(args.infile) as f:
            text = f.read()
    else:
        text = sys.stdin.read()

    result = convert_wikilinks(text)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(result)
    else:
        sys.stdout.write(result)


if __name__ == '__main__':
    main()
